### ISSUE TITLE
Plugin not loading in the beta version of Burp

### ISSUE THREAD

**Issue by obi-jon** [nccgroup/Decoder-Improved#11] opened 2019-01-24 16:54 UTC
Attempts to load the plugin with Beta v2.0.14 results in the following error:
 java.lang.NullPointerException
	at trust.nccgroup.decoderimproved.JsPrettifier.<init>(JsPrettifier.java:22)
	at trust.nccgroup.decoderimproved.PrettifyMode.<init>(PrettifyMode.java:18)
	at trust.nccgroup.decoderimproved.ModificationModeManager.<init>(ModificationModeManager.java:49)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderSegment.setupComponents(MultiDecoderTab.java:466)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderSegment.<init>(MultiDecoderTab.java:381)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderTab.setupComponents(MultiDecoderTab.java:264)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderTab.<init>(MultiDecoderTab.java:161)
	at trust.nccgroup.decoderimproved.MultiDecoderTab.addTab(MultiDecoderTab.java:87)
	at trust.nccgroup.decoderimproved.MultiDecoderTab.<init>(MultiDecoderTab.java:59)
	at trust.nccgroup.decoderimproved.ExtensionRoot.registerExtenderCallbacks(ExtensionRoot.java:17)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:9)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at burp.esk.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by justinmoore** [comment] 2019-02-01 16:17
hey @obi-jon,

Which JVM version are you using and did you build the plugin yourself, take it from the Git repo, or from the BApp store?

Thanks,
Justin

**Comment by obi-jon** [comment] 2019-02-01 19:01
I am using the Java that is packaged with the Burp Installer.  I am using the plugin from the BApp.
 
[BurpSuitePro/jre/release]
JAVA_VERSION="11.0.2"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se jdk.compiler jdk.crypto.ec jdk.pack jdk.unsupported jdk.zipfs"

**Comment by justinmoore** [comment] 2019-02-04 20:44
@obi-jon, Can you please try loading the JAR in the git repo instead of the BApp version? I'm having trouble reproducing this issue.

**Comment by obi-jon** [comment] 2019-02-05 16:18
Using the jar file from the repository results in the following error:
java.lang.NullPointerException
	at trust.nccgroup.decoderimproved.JsPrettifier.<init>(JsPrettifier.java:22)
	at trust.nccgroup.decoderimproved.PrettifyMode.<init>(PrettifyMode.java:18)
	at trust.nccgroup.decoderimproved.ModificationModeManager.<init>(ModificationModeManager.java:49)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderSegment.setupComponents(MultiDecoderTab.java:466)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderSegment.<init>(MultiDecoderTab.java:381)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderTab.setupComponents(MultiDecoderTab.java:264)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderTab.<init>(MultiDecoderTab.java:161)
	at trust.nccgroup.decoderimproved.MultiDecoderTab.addTab(MultiDecoderTab.java:87)
	at trust.nccgroup.decoderimproved.MultiDecoderTab.<init>(MultiDecoderTab.java:59)
	at trust.nccgroup.decoderimproved.ExtensionRoot.registerExtenderCallbacks(ExtensionRoot.java:17)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:9)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at burp.eso.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by xwuevernote** [comment] 2019-03-01 23:16
I am having the same issue now with v2.0.17beta. I installed the extension from BApp Store and here's my Errors:
`java.lang.NullPointerException
	at trust.nccgroup.decoderimproved.JsPrettifier.<init>(JsPrettifier.java:22)
	at trust.nccgroup.decoderimproved.PrettifyMode.<init>(PrettifyMode.java:18)
	at trust.nccgroup.decoderimproved.ModificationModeManager.<init>(ModificationModeManager.java:49)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderSegment.setupComponents(MultiDecoderTab.java:466)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderSegment.<init>(MultiDecoderTab.java:381)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderTab.setupComponents(MultiDecoderTab.java:264)
	at trust.nccgroup.decoderimproved.MultiDecoderTab$DecoderTab.<init>(MultiDecoderTab.java:161)
	at trust.nccgroup.decoderimproved.MultiDecoderTab.addTab(MultiDecoderTab.java:87)
	at trust.nccgroup.decoderimproved.MultiDecoderTab.<init>(MultiDecoderTab.java:59)
	at trust.nccgroup.decoderimproved.ExtensionRoot.registerExtenderCallbacks(ExtensionRoot.java:17)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:9)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at burp.ehq.lambda$registerExtenderCallbacks$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by xwuevernote** [comment] 2019-03-04 17:34
Looks like this is due to that Nashorn Script Engine is deprecated. A quick fix I did was to launch java with "-Dpolyglot.js.nashorn-compat=true" option

**Comment by noraj** [comment] 2019-04-03 16:53
Use java-8-openjdk instead of java-10-openjdk or  java-11-openjdk, it's not linked to this plugin specifically but to burp. A lot of burp feature including the proxy are not working or are bugged with newer version of java.

**Comment by zehuanncc** [comment] 2019-10-18 18:46
Closing this issue as it seems that Decoder-Improved works under the current version (Burp 2.1.04 in Java 8 and 11 as I tested). Feel free to reopen the issue if you still have trouble running it.

**Closed as completed by zehuanncc** 2019-10-18 18:46 UTC
